---
driver:
  name: vagrant

provisioner:
  name: dummy

platforms:
  - name: qwerty1979/mysql

verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - mysql_test.rb
